In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.model_selection import train_test_split

In [2]:
loan_data = pd.read_csv('loan_default.csv')

In [3]:
loan_data.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [4]:
loan_data.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='object')

In [5]:
loan_data.isna().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [8]:
loan_data.describe().round(2)

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00,255347.00
mean,43.50,82499.30,127578.87,574.26,59.54,2.50,13.49,36.03,0.50,0.12
std,14.99,38963.01,70840.71,158.90,34.64,1.12,6.64,16.97,0.23,0.32
min,18.00,15000.00,5000.00,300.00,0.00,1.00,2.00,12.00,0.10,0.00
25%,31.00,48825.50,66156.00,437.00,30.00,2.00,7.77,24.00,0.30,0.00
50%,43.00,82466.00,127556.00,574.00,60.00,2.00,13.46,36.00,0.50,0.00
75%,56.00,116219.00,188985.00,712.00,90.00,3.00,19.25,48.00,0.70,0.00
max,69.00,149999.00,249999.00,849.00,119.00,4.00,25.00,60.00,0.90,1.00

In [137]:
loan_data = loan_data.drop(columns=['LoanID'])

In [138]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Age             255347 non-null  int64
 1   Income          255347 non-null  int64
 2   LoanAmount      255347 non-null  int64
 3   CreditScore     255347 non-null  int64
 4   MonthsEmployed  255347 non-null  int64
 5   NumCreditLines  255347 non-null  int64
 6   InterestRate    255347 non-null  float64
 7   LoanTerm        255347 non-null  int64
 8   DTIRatio        255347 non-null  float64
 9   Education       255347 non-null  object
 10  EmploymentType  255347 non-null  object
 11  MaritalStatus   255347 non-null  object
 12  HasMortgage     255347 non-null  object
 13  HasDependents   255347 non-null  object
 14  LoanPurpose     255347 non-null  object
 15  HasCoSigner     255347 non-null  object
 16  Default         255347 non-null  int64
dtypes: float64(2), int64(8), object(7)
memory usage: 33.1+ MB

In [159]:
zmeienne_kategoryczne_nominalne = [
    'EmploymentType',
    'LoanPurpose',
    'Education',
    'MaritalStatus'
]
zmeienne_binarne = [
    'HasMortgage',
    'HasDependents',
    'HasCoSigner'
]
zmienne_ciagle_ilosciowe=[
    'Age',
    'Income',
    'LoanAmount',
    'CreditScore',
    'MonthsEmployed',
    'NumCreditLines',
    'DTIRatio',
    'Default'   # binary, ale numeryczna
]

In [160]:
loan_data[zmeienne_kategoryczne_nominalne].nunique()

EmploymentType    4
LoanPurpose       5
Education         4
MaritalStatus     3
dtype: int64

In [161]:
loan_data[zmeienne_kategoryczne_nominalne]= loan_data[zmeienne_kategoryczne_nominalne].astype('category')

In [162]:
loan_data.dtypes

Age                  int64
Income               int64
LoanAmount           int64
CreditScore          int64
MonthsEmployed       int64
NumCreditLines       int64
InterestRate       float64
LoanTerm             int64
DTIRatio           float64
Education         category
EmploymentType    category
MaritalStatus     category
HasMortgage          int32
HasDependents        int32
LoanPurpose       category
HasCoSigner          int32
Default              int64
dtype: object

In [163]:
loan_data[zmeienne_binarne]= pd.get_dummies(loan_data[zmeienne_binarne], drop_first=True)
loan_data[zmeienne_binarne]= loan_data[zmeienne_binarne].astype(int)

In [164]:
X= loan_data.drop(columns=['LoanTerm']) 

y= loan_data['LoanTerm']

In [165]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [166]:
X_train = pd.get_dummies(X_train, columns=zmeienne_kategoryczne_nominalne, drop_first=True)
X_test  = pd.get_dummies(X_test,  columns=zmeienne_kategoryczne_nominalne, drop_first=True)
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

In [167]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[zmienne_ciagle_ilosciowe] = scaler.fit_transform(
    X_train[zmienne_ciagle_ilosciowe]
)

X_test[zmienne_ciagle_ilosciowe] = scaler.transform(
    X_test[zmienne_ciagle_ilosciowe]
)
X_train.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,DTIRatio,HasMortgage,HasDependents,...,EmploymentType_Unemployed,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,Education_High School,Education_Master's,Education_PhD,MaritalStatus_Married,MaritalStatus_Single
137187,-1.699838,1.413785,1.151487,1.711544,-0.967182,-0.449530,10.47,1.339989,1,0,...,False,True,False,False,False,True,False,False,False,True
230334,0.234120,-0.649831,-1.715866,1.094714,-0.851727,-0.449530,19.72,0.993538,0,1,...,True,False,True,False,False,True,False,False,False,False
19687,-1.166333,0.046770,-0.458437,-0.762072,-1.515594,-0.449530,24.25,-0.219039,0,0,...,False,False,False,False,True,False,True,False,True,False
106509,0.634249,-0.839783,1.440049,-0.258537,1.370784,0.445809,14.44,-1.431615,1,0,...,False,False,False,False,False,False,False,False,False,True
242291,0.367496,0.845753,-1.488613,1.673779,-1.717640,1.341148,24.48,-1.691453,0,1,...,False,False,True,False,False,False,False,False,False,True

In [168]:
X_train.dtypes

Age                             float64
Income                          float64
LoanAmount                      float64
CreditScore                     float64
MonthsEmployed                  float64
NumCreditLines                  float64
InterestRate                    float64
DTIRatio                        float64
HasMortgage                       int32
HasDependents                     int32
HasCoSigner                       int32
Default                         float64
EmploymentType_Part-time           bool
EmploymentType_Self-employed       bool
EmploymentType_Unemployed          bool
LoanPurpose_Business               bool
LoanPurpose_Education              bool
LoanPurpose_Home                   bool
LoanPurpose_Other                  bool
Education_High School              bool
Education_Master's                 bool
Education_PhD                      bool
MaritalStatus_Married              bool
MaritalStatus_Single               bool
dtype: object

In [169]:
bool_cols = X_train.select_dtypes(include='bool').columns
X_train[bool_cols] = X_train[bool_cols].astype('int8')
X_test[bool_cols] = X_test[bool_cols].astype('int8')
X_train.dtypes

Age                             float64
Income                          float64
LoanAmount                      float64
CreditScore                     float64
MonthsEmployed                  float64
NumCreditLines                  float64
InterestRate                    float64
DTIRatio                        float64
HasMortgage                       int32
HasDependents                     int32
HasCoSigner                       int32
Default                         float64
EmploymentType_Part-time           int8
EmploymentType_Self-employed       int8
EmploymentType_Unemployed          int8
LoanPurpose_Business               int8
LoanPurpose_Education              int8
LoanPurpose_Home                   int8
LoanPurpose_Other                  int8
Education_High School              int8
Education_Master's                 int8
Education_PhD                      int8
MaritalStatus_Married              int8
MaritalStatus_Single               int8
dtype: object

In [170]:
import statsmodels.api as sm

X_train_sm = sm.add_constant(X_train, has_constant='add')
model = sm.OLS(y_train, X_train_sm).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               LoanTerm   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.4820
Date:                Sat, 17 Jan 2026   Prob (F-statistic):              0.984
Time:                        14:19:45   Log-Likelihood:            -8.6795e+05
No. Observations:              204277   AIC:                         1.736e+06
Df Residuals:                  204252   BIC:                         1.736e+06
Df Model:                          24
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                           36.0842      0.169    213.901      0.000      35.754      36.415
Age                              0.0158      0.038      0.414      0.679      -0.059       0.090
Income                          -0.0376      0.038     -0.999      0.318      -0.112       0.036
LoanAmount                       0.0373      0.038      0.990      0.322      -0.036       0.111
CreditScore                      0.0014      0.038      0.038      0.969      -0.072       0.075
MonthsEmployed                  -0.0123      0.038     -0.325      0.745      -0.086       0.062
NumCreditLines                   0.0027      0.038      0.072      0.943      -0.071       0.076
InterestRate                     0.0004      0.006      0.072      0.942      -0.011       0.012
DTIRatio                         0.0280      0.038      0.747      0.455      -0.045       0.102
HasMortgage                      0.0933      0.075      1.244      0.213      -0.054       0.240
HasDependents                    0.0222      0.075      0.296      0.767      -0.125       0.169
HasCoSigner                     -0.0077      0.075     -0.103      0.918      -0.155       0.139
Default                          0.0066      0.039      0.170      0.865      -0.070       0.083
EmploymentType_Part-time        -0.0154      0.106     -0.146      0.884      -0.223       0.192
EmploymentType_Self-employed    -0.0542      0.106     -0.510      0.610      -0.262       0.154
EmploymentType_Unemployed        0.0396      0.106      0.372      0.710      -0.169       0.248
LoanPurpose_Business            -0.0720      0.119     -0.607      0.544      -0.304       0.160
LoanPurpose_Education           -0.0396      0.119     -0.334      0.739      -0.272       0.193
LoanPurpose_Home                 0.0038      0.119      0.032      0.974      -0.229       0.236
LoanPurpose_Other                0.1239      0.119      1.044      0.296      -0.109       0.357
Education_High School           -0.0783      0.106     -0.739      0.460      -0.286       0.129
Education_Master's              -0.1567      0.106     -1.478      0.139      -0.364       0.051
Education_PhD                   -0.1097      0.106     -1.036      0.300      -0.317       0.098
MaritalStatus_Married           -0.0752      0.092     -0.819      0.413      -0.255       0.105
MaritalStatus_Single            -0.0524      0.092     -0.570      0.569      -0.232       0.128
==============================================================================
Omnibus:                   725211.231   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14310.133
Skew:                          -0.001   Prob(JB):                         0.00
Kurtosis:                       1.703   Cond. No.                         90.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.